kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configname }}
  namespace: {{ .Values.namespace }}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: 'Customized with a configmap!'